# Generated by Django 5.1.5 on 2025-01-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_user',
            field=models.ImageField(blank=True, default='profil/user.png', null=True, upload_to='profil/'),
        ),
    ]
