# Generated by Django 5.1.5 on 2025-02-09 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='leçon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='kamerapp.leçon'),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='leçon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jeux', to='kamerapp.leçon'),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='type',
            field=models.CharField(choices=[('reconstitution', 'Reconstitution de phrase'), ('quiz', 'Quiz'), ('association', 'Association de mots'), ('traduction', 'Traduction'), ('complétion', 'Complétion de dialogue')], max_length=50),
        ),
    ]
