# Generated by Django 5.1.5 on 2025-01-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='image_url_user',
        ),
        migrations.RemoveField(
            model_name='langue',
            name='image_url',
        ),
        migrations.AddField(
            model_name='customuser',
            name='image_user',
            field=models.ImageField(null=True, upload_to='profil/'),
        ),
        migrations.AddField(
            model_name='langue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Image_langue/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='aire',
            field=models.CharField(blank=True, default='vide', max_length=50),
        ),
    ]
