# Generated by Django 5.1.5 on 2025-01-26 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamerapp', '0002_remove_customuser_image_url_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='description',
        ),
        migrations.AddField(
            model_name='cours',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='vide', max_length=100)),
                ('cours', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='kamerapp.cours')),
            ],
        ),
    ]
