# Generated by Django 5.1.5 on 2025-01-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamerapp', '0002_alter_customuser_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_user',
            field=models.ImageField(blank=True, default='profil/utilisateur.png', null=True, upload_to='profil/'),
        ),
    ]
