# Generated by Django 5.1.5 on 2025-02-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamerapp', '0002_alter_exercice_leçon_alter_jeu_leçon_alter_jeu_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leçon',
            name='image_lecon',
            field=models.ImageField(blank=True, default='image_lecon/lesson.gif', null=True, upload_to='image_lecon/'),
        ),
        migrations.AddField(
            model_name='leçon',
            name='intro',
            field=models.TextField(default='vide', null=True),
        ),
    ]
