# Generated by Django 5.1.5 on 2025-01-31 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamerapp', '0003_alter_customuser_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_question',
            field=models.ImageField(blank=True, default='question/question.gif', null=True, upload_to='question/'),
        ),
    ]
