# Generated by Django 5.1.5 on 2025-01-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kamerapp', '0004_langue_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='slug',
        ),
    ]
