# Generated by Django 5.1.5 on 2025-02-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamerapp', '0004_activiterecente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activiterecente',
            name='type_activite',
            field=models.CharField(choices=[('lesson', 'Cours Terminé'), ('quiz', 'Quiz Répondu'), ('forum', 'Participation au Forum')], max_length=20),
        ),
    ]
