# Generated by Django 5.1.5 on 2025-01-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamerapp', '0005_quiz_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionnaire',
            name='image_question',
            field=models.ImageField(blank=True, default='dico/question.gif', null=True, upload_to='dico/'),
        ),
        migrations.AlterField(
            model_name='dictionnaire',
            name='mot_traditionnel',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
