# Generated by Django 5.1.5 on 2025-01-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamerapp', '0005_remove_cours_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langue',
            name='slug',
            field=models.SlugField(blank=True, default='Ewondo', unique=True),
        ),
    ]
