# Generated by Django 5.1.5 on 2025-01-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamerapp', '0006_dictionnaire_image_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionnaire',
            name='audio',
            field=models.FileField(default='dico/question.gif', null=True, upload_to='audios/'),
        ),
    ]
