# Generated by Django 5.1.5 on 2025-01-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kamerapp', '0006_alter_langue_slug'),
    ]

    operations = [
    ]
