# Generated by Django 5.1.5 on 2025-01-31 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kamerapp', '0007_dictionnaire_audio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionnaire',
            old_name='image_question',
            new_name='image',
        ),
    ]
