# Generated by Django 5.1.5 on 2025-02-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamerapp', '0008_rename_image_question_dictionnaire_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
