# Generated by Django 5.1.5 on 2025-01-26 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamerapp', '0008_cours_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leçon',
            name='cours',
        ),
        migrations.RemoveField(
            model_name='leçon',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='leçon',
            name='exercices',
        ),
        migrations.RemoveField(
            model_name='leçon',
            name='fichier_audio',
        ),
        migrations.RemoveField(
            model_name='leçon',
            name='ordre',
        ),
        migrations.RemoveField(
            model_name='leçon',
            name='type_leçon',
        ),
        migrations.RemoveField(
            model_name='leçon',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='leçon',
            name='chap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='kamerapp.chapitre'),
        ),
        migrations.AlterField(
            model_name='dictionnaire',
            name='mot_traditionnel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lang', to='kamerapp.langue'),
        ),
        migrations.AlterField(
            model_name='leçon',
            name='contenu',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='leçon',
            name='titre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
