# Generated by Django 5.1.5 on 2025-02-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamerapp', '0009_alter_cours_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='slug',
            field=models.SlugField(blank=True, default='Ewondo', unique=True),
        ),
    ]
