# Generated by Django 5.1.5 on 2025-01-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kamerapp', '0009_remove_leçon_cours_remove_leçon_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leçon',
        ),
    ]
