# Generated by Django 5.1.5 on 2025-01-26 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamerapp', '0010_delete_leçon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leçon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, null=True)),
                ('contenu', models.TextField()),
                ('chap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='kamerapp.chapitre')),
            ],
        ),
    ]
